# Generated by Django 4.1.5 on 2023-01-23 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=50, unique=True)),
                ('enrolled', models.CharField(max_length=100)),
                ('session', models.DateTimeField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.PositiveIntegerField(max_length=50, primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('student_email', models.EmailField(max_length=50, unique=True)),
                ('course', models.CharField(max_length=100)),
                ('student_year', models.DateField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('student_acc', models.IntegerField(max_length=100, primary_key=True, serialize=False)),
                ('amount', models.IntegerField(max_length=50)),
                ('date', models.DateField(max_length=50)),
                ('adm_no', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='School_AMS.student')),
            ],
        ),
    ]
